import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Sidebar from "./Components/sidebar/Sidebar";
import Globalstyles from "./providers/Globalstyles";
import ContextProvider from "./providers/ContextProvider";
const nunito = Nunito({ 
  weight: ["400","500","600","700","800","900"],
  subsets: ["latin"] });
import { ClerkProvider,auth } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const {userId} = auth();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>

      <body className={nunito.className}>
        <NextTopLoader
          height={20}
          color="27AE60"
          easing="cubic-bezier(.53,.21,0,1)"
        />
        <ContextProvider>
          <Globalstyles>
              {userId&&<Sidebar/>}
            <div className="w-full">{children}</div>
          </Globalstyles>
        </ContextProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
